In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.3.1+cu121


**CREATE TENSOR**

In [ ]:
scalar=torch.tensor(17)
scalar

tensor(17)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item

<function Tensor.item>

In [ ]:
vector = torch.tensor([2,2] )
vector

tensor([2, 2])

In [ ]:
matrix = torch.tensor([[2,2],
                      [2,2]])
matrix

tensor([[2, 2],
        [2, 2]])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
tensor = torch.tensor([[[2,2],
                      [1,3],
                      [4,6]]])
tensor

tensor([[[2, 2],
         [1, 3],
         [4, 6]]])

In [ ]:
tensor.shape

torch.Size([1, 3, 2])

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4294, 0.4134, 0.5195, 0.5680],
        [0.8509, 0.5777, 0.3880, 0.7070],
        [0.5037, 0.0380, 0.7917, 0.5475]])

In [ ]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

**create a range of tensor**

In [ ]:
#tạo 1 vecto chạy kieu nhu vong for
one_to_ten=torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#tạo 1 vecto như của one_to_ten
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Tensor datatypes**

In [ ]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
x=float_16_tensor*float_32_tensor

In [ ]:
x.dtype

torch.float32

In [ ]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
some_tensor=torch.rand(3,4)
some_tensor
#

tensor([[0.3893, 0.9149, 0.7989, 0.3055],
        [0.7316, 0.6489, 0.7212, 0.8208],
        [0.5502, 0.1499, 0.5471, 0.2816]])

In [ ]:
print(some_tensor)
print(f"datatype of tensor:{some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"device of tensor:{some_tensor.device}")


tensor([[0.3893, 0.9149, 0.7989, 0.3055],
        [0.7316, 0.6489, 0.7212, 0.8208],
        [0.5502, 0.1499, 0.5471, 0.2816]])
datatype of tensor:torch.float32
shape of tensor:torch.Size([3, 4])
device of tensor:cpu


In [ ]:
##Manipulating

In [3]:
##Create tensor
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [4]:
#Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [ ]:
#Substraction 10
tensor-10

tensor([-9, -8, -7])

In [ ]:
#Try out pytorvh in built functions
print(torch.mul(tensor,10))
print(torch.add(tensor,10))
print(torch.sub(tensor,10))
print(torch.div(tensor,10))

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


In [ ]:
##Matrix multiplkication
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value +=tensor[i]*tensor[i]
print(value)


tensor(14)
CPU times: user 1.38 ms, sys: 21 µs, total: 1.4 ms
Wall time: 1.28 ms


**X ma tran**

In [7]:
torch.matmul(torch.rand(2,3),torch.rand(3,3))

tensor([[0.8748, 0.6777, 1.4146],
        [0.7743, 0.7334, 1.2616]])

In [9]:
##Shapes for maxtrix multipliaction
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

**Finding the min , max , mean,...(tensor aggregation)**

In [11]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
x.max(),x.min()

(tensor(90), tensor(0))

In [13]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [15]:
x.argmin(),x[1]

(tensor(0), tensor(10))

**Réhaping,stacking,squeezing and unsquezzing**

In [16]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [20]:
x_reshaped=x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [21]:
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [22]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [23]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [24]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [27]:
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [30]:
x_squeezed=x_reshaped.squeeze()

In [31]:
x_unsquezzed=x_squeezed.unsqueeze(dim=0)
x_unsquezzed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [33]:
x_original=torch.rand(size=(224,224,3))
x_permuted=x_original.permute((2,1,0))
x_original.shape,x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))