In [1]:
!nvidia-smi

Wed Sep 11 15:11:06 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
torch.cuda.device_count()

1

In [5]:
tensor=torch.tensor([1,2,3],device="cpu")
print(tensor,tensor.device)


tensor([1, 2, 3]) cpu


In [6]:
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [7]:
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [16]:
##Create random tensor with shape (7,7)
tensor_rand=torch.rand(7,7)
tensor_rand

tensor([[0.0015, 0.7733, 0.4167, 0.9328, 0.1896, 0.2292, 0.6716],
        [0.3913, 0.4299, 0.5088, 0.8303, 0.9248, 0.1632, 0.5355],
        [0.6946, 0.7051, 0.6494, 0.2676, 0.7523, 0.1380, 0.4609],
        [0.3721, 0.2810, 0.5663, 0.5970, 0.4305, 0.8135, 0.0472],
        [0.5538, 0.0174, 0.9834, 0.3068, 0.5763, 0.8876, 0.3781],
        [0.2420, 0.3727, 0.2562, 0.0907, 0.3662, 0.8624, 0.1109],
        [0.0068, 0.2149, 0.6208, 0.2695, 0.3581, 0.8137, 0.8675]])

In [17]:
tensor_rand1=torch.rand(1,7)
tensor_rand1

tensor([[0.3209, 0.5110, 0.6942, 0.1116, 0.6709, 0.0225, 0.2372]])

In [18]:
mul=torch.matmul(tensor_rand,tensor_rand1.T)
mul.shape

torch.Size([7, 1])

In [19]:
random_seed=0
generator=torch.Generator().manual_seed(random_seed)
tensor_rand=torch.rand((7,7))
tensor_rand

tensor([[0.2727, 0.1906, 0.0321, 0.6469, 0.0124, 0.1235, 0.2176],
        [0.1680, 0.9424, 0.0998, 0.6423, 0.8512, 0.5932, 0.2724],
        [0.1846, 0.1344, 0.5678, 0.8397, 0.5161, 0.2136, 0.2377],
        [0.4883, 0.2229, 0.3665, 0.2589, 0.3289, 0.5603, 0.1249],
        [0.0230, 0.1016, 0.2727, 0.9338, 0.6080, 0.0976, 0.8046],
        [0.2377, 0.6005, 0.5223, 0.5641, 0.5434, 0.2178, 0.7981],
        [0.6808, 0.7185, 0.3802, 0.8369, 0.5108, 0.7288, 0.5120]])

In [22]:
tensor_rand2=torch.rand((1,7))
tensor_rand2
mul=torch.matmul(tensor_rand,tensor_rand2.T)
mul

tensor([[1.0216],
        [1.2811],
        [1.5288],
        [1.1219],
        [1.7328],
        [1.7617],
        [2.1844]])

In [24]:
import torch
torch.cuda.manual_seed(1234)

In [29]:
torch.cuda.manual_seed(1234)
ran_seed=torch.rand(2,3)
ran_seed2=torch.rand(2,3)

ran_seed2=ran_seed2.to(device)
ran_seed2
ran_seed=ran_seed.to(device)
ran_seed

tensor([[0.0672, 0.1977, 0.2200],
        [0.8793, 0.4251, 0.8037]], device='cuda:0')

In [30]:
mul=torch.matmul(ran_seed,ran_seed2.T)
mul

tensor([[0.3373, 0.2671],
        [1.5903, 1.1299]], device='cuda:0')

In [31]:
mul.max(),mul.min()

(tensor(1.5903, device='cuda:0'), tensor(0.2671, device='cuda:0'))

In [35]:
random_seed=7
tensor_rand=torch.rand(1,1,1,10) # This creates a 4-dimensional tensor
torch.manual_seed(random_seed)
new_tensor=tensor_rand[0][0][0][:] # Access elements from tensor_rand
new_tensor, new_tensor.size

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 <function Tensor.size>)