In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.3.1+cu121


**CREATE TENSOR**

In [4]:
scalar=torch.tensor(17)
scalar

tensor(17)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item

<function Tensor.item>

In [ ]:
vector = torch.tensor([2,2] )
vector

tensor([2, 2])

In [ ]:
matrix = torch.tensor([[2,2],
                      [2,2]])
matrix

tensor([[2, 2],
        [2, 2]])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [5]:
tensor = torch.tensor([[[2,2],
                      [1,3],
                      [4,6]]])
tensor

tensor([[[2, 2],
         [1, 3],
         [4, 6]]])

In [7]:
tensor.shape

torch.Size([1, 3, 2])

In [10]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4294, 0.4134, 0.5195, 0.5680],
        [0.8509, 0.5777, 0.3880, 0.7070],
        [0.5037, 0.0380, 0.7917, 0.5475]])

In [12]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
ones.dtype

torch.float32

**create a range of tensor**

In [16]:
#tạo 1 vecto chạy kieu nhu vong for
one_to_ten=torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
#tạo 1 vecto như của one_to_ten
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Tensor datatypes**

In [21]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
x=float_16_tensor*float_32_tensor

In [28]:
x.dtype

torch.float32

In [29]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [30]:
some_tensor=torch.rand(3,4)
some_tensor
#

tensor([[0.3893, 0.9149, 0.7989, 0.3055],
        [0.7316, 0.6489, 0.7212, 0.8208],
        [0.5502, 0.1499, 0.5471, 0.2816]])

In [32]:
print(some_tensor)
print(f"datatype of tensor:{some_tensor.dtype}")
print(f"shape of tensor:{some_tensor.shape}")
print(f"device of tensor:{some_tensor.device}")


tensor([[0.3893, 0.9149, 0.7989, 0.3055],
        [0.7316, 0.6489, 0.7212, 0.8208],
        [0.5502, 0.1499, 0.5471, 0.2816]])
datatype of tensor:torch.float32
shape of tensor:torch.Size([3, 4])
device of tensor:cpu


In [ ]:
##Manipulating

In [33]:
##Create tensor
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [37]:
#Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [38]:
#Substraction 10
tensor-10

tensor([-9, -8, -7])

In [41]:
#Try out pytorvh in built functions
print(torch.mul(tensor,10))
print(torch.add(tensor,10))
print(torch.sub(tensor,10))
print(torch.div(tensor,10))

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


In [42]:
##Matrix multiplkication
torch.matmul(tensor,tensor)

tensor(14)

In [43]:
%%time
value=0
for i in range(len(tensor)):
  value +=tensor[i]*tensor[i]
print(value)


tensor(14)
CPU times: user 1.38 ms, sys: 21 µs, total: 1.4 ms
Wall time: 1.28 ms
