In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.3.1+cu121


**CREATE TENSOR**

In [5]:
scalar=torch.tensor(17)
scalar

tensor(17)

In [6]:
scalar.ndim

0

In [8]:
scalar.item

<function Tensor.item>

In [12]:
vector = torch.tensor([2,2] )
vector

tensor([2, 2])

In [13]:
matrix = torch.tensor([[2,2],
                      [2,2]])
matrix

tensor([[2, 2],
        [2, 2]])

In [14]:
matrix.shape

torch.Size([2, 2])

In [18]:
tensor = torch.tensor([[[2,2],
                      [1,3],
                      [4,6]]])
tensor

tensor([[[2, 2],
         [1, 3],
         [4, 6]]])

In [19]:
tensor.shape

torch.Size([1, 3, 2])